name: Auto Build

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - containers/**
      - template/**
  schedule:
    - cron: '0 9 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Enable QEMU for ARM builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Enable Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Update Images
        run: ./bin/01-update-images ${{ secrets.GITHUB_TOKEN }}

      - name: Update Readme
        run: ./bin/02-update-readme

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: "nekosunevr-ci"
          author_email: nekosunevr-ci@nekosunevr.co.uk
          message: 'CI: Autobuild Repo'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ðŸ”¥ Multi-arch build (AMD64 + ARM64)
      - name: Build and Push Images to ghcr.io
        run: ./bin/03-build-images push
        env:
          CI_REGISTRY_IMAGE: ${{ env.IMAGE_NAME }}
