name: Auto Build

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - containers/**
      - template/**
  schedule:
    - cron: '0 9 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Enable QEMU for ARM builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Enable Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Images
        run: ./bin/01-update-images ${{ secrets.GITHUB_TOKEN }}

      - name: Update Readme
        run: ./bin/02-update-readme

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: "bskrtich-ci"
          author_email: bskrtich-ci@bearded.io
          message: 'CI: Autobuild Repo'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ðŸ”¥ Multi-arch build (AMD64 + ARM64)
      - name: Build and Push Multi-Arch (ghcr.io)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nekosuneprojects/terraria:latest

      - name: Build and Push Multi-Arch (Docker Hub)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nekosuneprojects/terraria:latest


  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Windows Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: windows/amd64
          tags: nekosuneprojects/terraria:windows-latest
